version: "3.9"
services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: "mongodb://mongo:27017"
    depends_on:
      - mongo

  mongo:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
