replicaCounts:
  nodejsApp: 1
  mongoDB: 1

nodejsApp:
  name: nodejs-app
  image:
    repository: registry.ocp.octopus.local:5000/frontend-app
    tag: latest
  containerPort: 3000
  env:
    mongoUri: mongodb://mongo:27017

mongoDB:
  name: mongo
  image:
    repository: docker.io/mongo
    tag: latest
  containerPort: 27017
  volume:
    configMapName: mongo-init-script
    scriptName: init-mongo.js

services:
  nodejsApp:
    port: 3000
    targetPort: 3000
  mongo:
    port: 27017
    targetPort: 27017

ingress:
  className: nginx
  host: "app.omsad.xyz"

